[package]
name = "kva"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "small valve kv text and binary parser"
rust-version = "1.88"

[features]
default = ["std", "text", "binary", "serde"]

std = ["serde?/std"]
text = []
binary = []
serde = ["dep:serde"]

full-fixtures = []

[dependencies]
serde = { version = "1", default-features = false, features = [
    "derive",
    "alloc",
], optional = true }

[dev-dependencies]
criterion = { version = "0.8" }
proptest = { version = "1.9" }
# kv 
keyvalues-parser = { version = "0.2.4" }
valve-keyvalue = { version = "1.0.3" }
vdf-reader = { version = "0.3.3" }

[[bench]]
name = "parse"
harness = false
