[package]
name = "kva-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
kva = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "text"
path = "fuzz_targets/text.rs"
test = false
doc = false
bench = false

[[bin]]
name = "binary"
path = "fuzz_targets/binary.rs"
test = false
doc = false
bench = false
